In [3]:
x = np.array(12)

In [4]:
x.ndim
# ранг

0

In [5]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [6]:
x.ndim

1

In [7]:
x = np.array([[5, 78, 2, 34, 0], [6, 79, 3, 35, 1],[7, 80, 4, 36, 2]])
x

array([[ 5, 78,  2, 34,  0],
       [ 6, 79,  3, 35,  1],
       [ 7, 80,  4, 36,  2]])

In [8]:
x.ndim

2

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
x

array([[[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]],

       [[ 5, 78,  2, 34,  0],
        [ 6, 79,  3, 35,  1],
        [ 7, 80,  4, 36,  2]]])

In [1]:
digit = train_images[4]
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()


In [ ]:
my_slice = train_images[10:30]
print(my_slice.shape)

In [ ]:
my_slice = train_images[:, 14:, 14:]
print(my_slice.shape)

Допускается использовать и отрицательные индексы. Так же как отрицательные индексы в списках на Python, они будут откладываться от конца текущей оси. Например, вот так можно обрезать все изображения, оставив только квадрат 14 × 14 пикселов в центре:

In [ ]:
my_slice = train_images[:, 7:-7, 7:-7]
print(my_slice.shape)

_______________

In [ ]:
batch = train_images[128:256]

In [ ]:
#output = relu(dot(W, input) + b)

In [ ]:
def naive_relu(x):
    assert len(x.shape) == 2 #Убедиться, что x — двумерный тензор Numpy
    x = x.copy() #Исключить затирание исходного тензора 
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0) 
    return x

In [ ]:
def naive_add(x, y):
    assert len(x.shape) == 2 #Убедиться, что x и y — двумерные тензоры Numpy assert x.shape == y.shape
    x = x.copy() #Исключить затирание исходного тензора
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j] 
    return x

In [ ]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

In [ ]:
print(x.shape)

In [ ]:
x = x.reshape((6,1))
x

In [ ]:
x = x.reshape((2,3))
x

In [ ]:
x = np.zeros((300, 20))
print(x.shape)

In [ ]:
# транспонирование
x = np.transpose(x)

In [ ]:
print(x.shape)

# ИТОГ

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist

from keras import models
from keras import layers

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images = train_images.reshape((60000, 28 * 28)) 
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28)) 
test_images = test_images.astype('float32') / 255

#Входные данные типа float32 хранятся в тензорах Numpy,
#имеющих форму (60000, 784) (обучающие данные) и
#(10000, 784) (контрольные данные) соответственно.

In [4]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

#Эта сеть состоит из цепочки двух слоев Dense, каждый из которых применяет к входным данным 
#несколько простых операций с тензорами, и что эти операции вовлекают весовые тензоры. 
#Весовые тензоры, являющиеся атрибутами слоев, — это место, где запоминаются знания, накопленные сетью.

In [5]:
#Вот как выглядел этап компиляции:
network.compile(optimizer='rmsprop', 
                loss='categorical_crossentropy',
                metrics=['accuracy'])

#categorical_crossentropy — это функция потерь, 
#которая используется в качестве сигнала обратной связи для обучения весовых тензоров 
#и которую этап обучения стремится свести к минимуму. 
#Вы также знаете, что снижение потерь достигается за счет применения алгоритма стохастического градиентного спуска
#на небольших пакетах. Точные правила, управляющие конкретным применением градиентного спуска,
#определяются оптимизатором rmsprop, который передается в первом аргументе.

In [6]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels) 
test_labels = to_categorical(test_labels)

#кодирование меток категорий

In [7]:
#Наконец, вот как выглядел цикл обучения:
network.fit(train_images, train_labels, epochs=6, batch_size=256)

Epoch 1/6
60000/60000 [==============================] - 2s 39us/step - loss: 0.3122 - accuracy: 0.9112
Epoch 2/6
60000/60000 [==============================] - 2s 36us/step - loss: 0.1303 - accuracy: 0.9621
Epoch 3/6
60000/60000 [==============================] - 2s 35us/step - loss: 0.0856 - accuracy: 0.9748
Epoch 4/6
60000/60000 [==============================] - 2s 36us/step - loss: 0.0623 - accuracy: 0.9814
Epoch 5/6
60000/60000 [==============================] - 2s 36us/step - loss: 0.0475 - accuracy: 0.9862
Epoch 6/6
60000/60000 [==============================] - 2s 38us/step - loss: 0.0367 - accuracy: 0.9896


In [8]:
#Теперь проверим, как модель распознает контрольный набор
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 0s 47us/step
test_acc: 0.9761000275611877


‰‰Функция потерь — это величина, которую требуется свести к минимуму в ходе обучения, поэтому она должна представлять собой меру успеха для решаемой вами задачи.


‰‰Оптимизатор определяет точный способ использования градиента потерь для изменения параметров: например, это может быть оптимизатор RMSProp, реа- лизующий градиентный спуск с импульсом, и др.